// AUTO-GENERATED by tools/gen-l2-xml-drops.mjs — do not edit by hand.
import type { DropEntry } from "../../combat/types";

export type L2XmlNpcDrops = { drops: DropEntry[]; spoil: DropEntry[] };

export const L2_XML_DROPS_BY_NPC: Record<number, L2XmlNpcDrops> = {
  "18001": {
    drops: [
      {
        id: "l2item_2397",
        kind: "equipment",
        chance: 0.000012,
        min: 1,
        max: 1,
        chancePerMillion: 12,
        l2ItemId: 2397,
        displayName: "Tunic of Zubei"
      },
      {
        id: "l2item_2402",
        kind: "equipment",
        chance: 0.000019,
        min: 1,
        max: 1,
        chancePerMillion: 19,
        l2ItemId: 2402,
        displayName: "Stockings of Zubei"
      },
      {
        id: "l2item_2406",
        kind: "equipment",
        chance: 0.000008,
        min: 1,
        max: 1,
        chancePerMillion: 8,
        l2ItemId: 2406,
        displayName: "Avadon Robe"
      },
      {
        id: "l2item_1419",
        kind: "resource",
        chance: 0.2,
        min: 1,
        max: 1,
        chancePerMillion: 200000,
        l2ItemId: 1419,
        displayName: "Blood Mark"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.166667,
        min: 1,
        max: 1,
        chancePerMillion: 166667,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.0625,
        min: 1,
        max: 1,
        chancePerMillion: 62500,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "l2item_1878",
        kind: "resource",
        chance: 0.037037,
        min: 1,
        max: 1,
        chancePerMillion: 37037,
        l2ItemId: 1878,
        displayName: "Braided Hemp"
      },
      {
        id: "high_grade_suede",
        kind: "resource",
        chance: 0.007092,
        min: 1,
        max: 1,
        chancePerMillion: 7092,
        l2ItemId: 1885,
        displayName: "High Grade Suede"
      },
      {
        id: "l2item_1889",
        kind: "resource",
        chance: 0.005435,
        min: 1,
        max: 1,
        chancePerMillion: 5435,
        l2ItemId: 1889,
        displayName: "Compound Braid"
      },
      {
        id: "l2item_4069",
        kind: "resource",
        chance: 0.002102,
        min: 1,
        max: 1,
        chancePerMillion: 2102,
        l2ItemId: 4069,
        displayName: "Tunic of Zubei Fabric"
      },
      {
        id: "l2item_4070",
        kind: "resource",
        chance: 0.003192,
        min: 1,
        max: 1,
        chancePerMillion: 3192,
        l2ItemId: 4070,
        displayName: "Stockings of Zubei Fabric"
      },
      {
        id: "l2item_4071",
        kind: "resource",
        chance: 0.001615,
        min: 1,
        max: 1,
        chancePerMillion: 1615,
        l2ItemId: 4071,
        displayName: "Avadon Robe Fabric"
      },
      {
        id: "l2item_4197",
        kind: "resource",
        chance: 0.000008,
        min: 1,
        max: 1,
        chancePerMillion: 8,
        l2ItemId: 4197,
        displayName: "Recipe: Demon Dagger"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 765,
        max: 1528,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1806",
        kind: "resource",
        chance: 0.010868,
        min: 1,
        max: 1,
        chancePerMillion: 10868,
        l2ItemId: 1806,
        displayName: "Recipe: Soulshot: B-Grade"
      }
    ]
  },
  "20001": {
    drops: [],
    spoil: []
  },
  "20002": {
    drops: [],
    spoil: []
  },
  "20003": {
    drops: [
      {
        id: "l2item_112",
        kind: "equipment",
        chance: 0.079637,
        min: 1,
        max: 1,
        chancePerMillion: 79637,
        l2ItemId: 112,
        displayName: "Apprentice's Earring"
      },
      {
        id: "l2item_116",
        kind: "equipment",
        chance: 0.118249,
        min: 1,
        max: 1,
        chancePerMillion: 118249,
        l2ItemId: 116,
        displayName: "Magic Ring"
      },
      {
        id: "l2item_118",
        kind: "equipment",
        chance: 0.059125,
        min: 1,
        max: 1,
        chancePerMillion: 59125,
        l2ItemId: 118,
        displayName: "Necklace of Magic"
      },
      {
        id: "l2item_1788",
        kind: "resource",
        chance: 0.007805,
        min: 1,
        max: 1,
        chancePerMillion: 7805,
        l2ItemId: 1788,
        displayName: "Recipe: Bow"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.019512,
        min: 1,
        max: 1,
        chancePerMillion: 19512,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.009756,
        min: 1,
        max: 1,
        chancePerMillion: 9756,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.006504,
        min: 1,
        max: 1,
        chancePerMillion: 6504,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "thread",
        kind: "resource",
        chance: 0.019512,
        min: 1,
        max: 1,
        chancePerMillion: 19512,
        l2ItemId: 1868,
        displayName: "Thread"
      },
      {
        id: "silver_nugget",
        kind: "resource",
        chance: 0.003903,
        min: 1,
        max: 1,
        chancePerMillion: 3903,
        l2ItemId: 1873,
        displayName: "Silver Nugget"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 30,
        max: 42,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_116",
        kind: "resource",
        chance: 0.343131,
        min: 1,
        max: 1,
        chancePerMillion: 343131,
        l2ItemId: 116,
        displayName: "Magic Ring"
      },
      {
        id: "l2item_1786",
        kind: "resource",
        chance: 0.045293,
        min: 1,
        max: 1,
        chancePerMillion: 45293,
        l2ItemId: 1786,
        displayName: "Recipe: Broad Sword"
      },
      {
        id: "charcoal",
        kind: "resource",
        chance: 0.056617,
        min: 1,
        max: 1,
        chancePerMillion: 56617,
        l2ItemId: 1871,
        displayName: "Charcoal"
      }
    ]
  },
  "20004": {
    drops: [
      {
        id: "l2item_1119",
        kind: "equipment",
        chance: 0.005045,
        min: 1,
        max: 1,
        chancePerMillion: 5045,
        l2ItemId: 1119,
        displayName: "Short Leather Gloves"
      },
      {
        id: "l2item_1122",
        kind: "equipment",
        chance: 0.005044,
        min: 1,
        max: 1,
        chancePerMillion: 5044,
        l2ItemId: 1122,
        displayName: "Cotton Shoes"
      },
      {
        id: "l2item_1129",
        kind: "equipment",
        chance: 0.005044,
        min: 1,
        max: 1,
        chancePerMillion: 5044,
        l2ItemId: 1129,
        displayName: "Crude Leather Shoes"
      },
      {
        id: "l2item_1666",
        kind: "resource",
        chance: 0.005104,
        min: 1,
        max: 1,
        chancePerMillion: 5104,
        l2ItemId: 1666,
        displayName: "Recipe: Wooden Arrow"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.010206,
        min: 1,
        max: 1,
        chancePerMillion: 10206,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "charcoal",
        kind: "resource",
        chance: 0.015309,
        min: 1,
        max: 1,
        chancePerMillion: 15309,
        l2ItemId: 1871,
        displayName: "Charcoal"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 41,
        max: 58,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "suede",
        kind: "resource",
        chance: 0.051827,
        min: 1,
        max: 1,
        chancePerMillion: 51827,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "l2item_2005",
        kind: "resource",
        chance: 0.005553,
        min: 1,
        max: 1,
        chancePerMillion: 5553,
        l2ItemId: 2005,
        displayName: "Broadsword Blade"
      },
      {
        id: "l2item_2006",
        kind: "resource",
        chance: 0.005553,
        min: 1,
        max: 1,
        chancePerMillion: 5553,
        l2ItemId: 2006,
        displayName: "Willow Staff Head"
      }
    ]
  },
  "20005": {
    drops: [
      {
        id: "l2item_19",
        kind: "equipment",
        chance: 0.009012,
        min: 1,
        max: 1,
        chancePerMillion: 9012,
        l2ItemId: 19,
        displayName: "Small Shield"
      },
      {
        id: "l2item_42",
        kind: "equipment",
        chance: 0.006311,
        min: 1,
        max: 1,
        chancePerMillion: 6311,
        l2ItemId: 42,
        displayName: "Leather Cap"
      },
      {
        id: "l2item_17",
        kind: "resource",
        chance: 0.071865,
        min: 10,
        max: 30,
        chancePerMillion: 71865,
        l2ItemId: 17,
        displayName: "Wooden Arrow"
      },
      {
        id: "l2item_1789",
        kind: "resource",
        chance: 0.002657,
        min: 1,
        max: 1,
        chancePerMillion: 2657,
        l2ItemId: 1789,
        displayName: "Recipe: Cedar Staff"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.014373,
        min: 1,
        max: 1,
        chancePerMillion: 14373,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.014373,
        min: 1,
        max: 1,
        chancePerMillion: 14373,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 51,
        max: 72,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1060",
        kind: "resource",
        chance: 0.216259,
        min: 1,
        max: 1,
        chancePerMillion: 216259,
        l2ItemId: 1060,
        displayName: "Lesser Healing Potion"
      },
      {
        id: "l2item_1666",
        kind: "resource",
        chance: 0.032439,
        min: 1,
        max: 1,
        chancePerMillion: 32439,
        l2ItemId: 1666,
        displayName: "Recipe: Wooden Arrow"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.064878,
        min: 1,
        max: 1,
        chancePerMillion: 64878,
        l2ItemId: 1866,
        displayName: "Suede"
      }
    ]
  },
  "20006": {
    drops: [
      {
        id: "l2item_14",
        kind: "equipment",
        chance: 0.000607,
        min: 1,
        max: 1,
        chancePerMillion: 607,
        l2ItemId: 14,
        displayName: "Bow"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.016852,
        min: 1,
        max: 1,
        chancePerMillion: 16852,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "charcoal",
        kind: "resource",
        chance: 0.025278,
        min: 1,
        max: 1,
        chancePerMillion: 25278,
        l2ItemId: 1871,
        displayName: "Charcoal"
      },
      {
        id: "l2item_2007",
        kind: "resource",
        chance: 0.002709,
        min: 1,
        max: 1,
        chancePerMillion: 2709,
        l2ItemId: 2007,
        displayName: "Bow Shaft"
      },
      {
        id: "l2item_2136",
        kind: "resource",
        chance: 0.007435,
        min: 1,
        max: 1,
        chancePerMillion: 7435,
        l2ItemId: 2136,
        displayName: "Recipe: Cokes"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 69,
        max: 94,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_113",
        kind: "resource",
        chance: 0.031655,
        min: 1,
        max: 1,
        chancePerMillion: 31655,
        l2ItemId: 113,
        displayName: "Mystic's Earring"
      },
      {
        id: "l2item_1060",
        kind: "resource",
        chance: 0.285245,
        min: 1,
        max: 1,
        chancePerMillion: 285245,
        l2ItemId: 1060,
        displayName: "Lesser Healing Potion"
      },
      {
        id: "l2item_2006",
        kind: "resource",
        chance: 0.009169,
        min: 1,
        max: 1,
        chancePerMillion: 9169,
        l2ItemId: 2006,
        displayName: "Willow Staff Head"
      }
    ]
  },
  "20007": {
    drops: [
      {
        id: "l2item_22",
        kind: "equipment",
        chance: 0.003619,
        min: 1,
        max: 1,
        chancePerMillion: 3619,
        l2ItemId: 22,
        displayName: "Leather Shirt"
      },
      {
        id: "l2item_29",
        kind: "equipment",
        chance: 0.005786,
        min: 1,
        max: 1,
        chancePerMillion: 5786,
        l2ItemId: 29,
        displayName: "Leather Pants"
      },
      {
        id: "l2item_1796",
        kind: "resource",
        chance: 0.036869,
        min: 1,
        max: 1,
        chancePerMillion: 36869,
        l2ItemId: 1796,
        displayName: "Recipe: Leather Tunic"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.058621,
        min: 1,
        max: 1,
        chancePerMillion: 58621,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "iron_ore",
        kind: "resource",
        chance: 0.029311,
        min: 1,
        max: 1,
        chancePerMillion: 29311,
        l2ItemId: 1869,
        displayName: "Iron Ore"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 80,
        max: 108,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1122",
        kind: "resource",
        chance: 0.049042,
        min: 1,
        max: 1,
        chancePerMillion: 49042,
        l2ItemId: 1122,
        displayName: "Cotton Shoes"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.099228,
        min: 1,
        max: 1,
        chancePerMillion: 99228,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "stone_of_purity",
        kind: "resource",
        chance: 0.009923,
        min: 1,
        max: 1,
        chancePerMillion: 9923,
        l2ItemId: 1875,
        displayName: "Stone of Purity"
      }
    ]
  },
  "20008": {
    drops: [
      {
        id: "l2item_255",
        kind: "equipment",
        chance: 0.000244,
        min: 1,
        max: 1,
        chancePerMillion: 244,
        l2ItemId: 255,
        displayName: "Fox Claw Gloves"
      },
      {
        id: "l2item_2371",
        kind: "equipment",
        chance: 0.000517,
        min: 1,
        max: 1,
        chancePerMillion: 517,
        l2ItemId: 2371,
        displayName: "Fist of Butcher"
      },
      {
        id: "l2item_1792",
        kind: "resource",
        chance: 0.003228,
        min: 1,
        max: 1,
        chancePerMillion: 3228,
        l2ItemId: 1792,
        displayName: "Recipe: Short Spear"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.043891,
        min: 1,
        max: 1,
        chancePerMillion: 43891,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.043891,
        min: 1,
        max: 1,
        chancePerMillion: 43891,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 114,
        max: 168,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1793",
        kind: "resource",
        chance: 0.016388,
        min: 1,
        max: 1,
        chancePerMillion: 16388,
        l2ItemId: 1793,
        displayName: "Recipe: Sword of Reflection"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.222882,
        min: 1,
        max: 1,
        chancePerMillion: 222882,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "charcoal",
        kind: "resource",
        chance: 0.222882,
        min: 1,
        max: 1,
        chancePerMillion: 222882,
        l2ItemId: 1871,
        displayName: "Charcoal"
      }
    ]
  },
  "20021": {
    drops: [
      {
        id: "l2item_9",
        kind: "equipment",
        chance: 0.000163,
        min: 1,
        max: 1,
        chancePerMillion: 163,
        l2ItemId: 9,
        displayName: "Cedar Staff"
      },
      {
        id: "l2item_154",
        kind: "equipment",
        chance: 0.000163,
        min: 1,
        max: 1,
        chancePerMillion: 163,
        l2ItemId: 154,
        displayName: "Dwarven Mace"
      },
      {
        id: "l2item_1060",
        kind: "resource",
        chance: 0.073151,
        min: 1,
        max: 1,
        chancePerMillion: 73151,
        l2ItemId: 1060,
        displayName: "Lesser Healing Potion"
      },
      {
        id: "l2item_1798",
        kind: "resource",
        chance: 0.032273,
        min: 1,
        max: 1,
        chancePerMillion: 32273,
        l2ItemId: 1798,
        displayName: "Recipe: Leather Helmet"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.032918,
        min: 1,
        max: 1,
        chancePerMillion: 32918,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.032918,
        min: 1,
        max: 1,
        chancePerMillion: 32918,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "l2item_2008",
        kind: "resource",
        chance: 0.001708,
        min: 1,
        max: 1,
        chancePerMillion: 1708,
        l2ItemId: 2008,
        displayName: "Cedar Staff Head"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 114,
        max: 168,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1792",
        kind: "resource",
        chance: 0.016388,
        min: 1,
        max: 1,
        chancePerMillion: 16388,
        l2ItemId: 1792,
        displayName: "Recipe: Short Spear"
      },
      {
        id: "l2item_1793",
        kind: "resource",
        chance: 0.016388,
        min: 1,
        max: 1,
        chancePerMillion: 16388,
        l2ItemId: 1793,
        displayName: "Recipe: Sword of Reflection"
      },
      {
        id: "l2item_1921",
        kind: "resource",
        chance: 0.143795,
        min: 1,
        max: 1,
        chancePerMillion: 143795,
        l2ItemId: 1921,
        displayName: "Leather Shoes Texture"
      }
    ]
  },
  "20030": {
    drops: [
      {
        id: "l2item_216",
        kind: "equipment",
        chance: 0.000253,
        min: 1,
        max: 1,
        chancePerMillion: 253,
        l2ItemId: 216,
        displayName: "Dirk"
      },
      {
        id: "l2item_1793",
        kind: "resource",
        chance: 0.003354,
        min: 1,
        max: 1,
        chancePerMillion: 3354,
        l2ItemId: 1793,
        displayName: "Recipe: Sword of Reflection"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.045611,
        min: 1,
        max: 1,
        chancePerMillion: 45611,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.045611,
        min: 1,
        max: 1,
        chancePerMillion: 45611,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "l2item_2009",
        kind: "resource",
        chance: 0.002427,
        min: 1,
        max: 1,
        chancePerMillion: 2427,
        l2ItemId: 2009,
        displayName: "Dirk Blade"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 116,
        max: 177,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1794",
        kind: "resource",
        chance: 0.01703,
        min: 1,
        max: 1,
        chancePerMillion: 17030,
        l2ItemId: 1794,
        displayName: "Recipe: Forest Bow"
      },
      {
        id: "l2item_1798",
        kind: "resource",
        chance: 0.227072,
        min: 1,
        max: 1,
        chancePerMillion: 227072,
        l2ItemId: 1798,
        displayName: "Recipe: Leather Helmet"
      },
      {
        id: "soulshot_ng",
        kind: "resource",
        chance: 0.617635,
        min: 1,
        max: 1,
        chancePerMillion: 617635,
        l2ItemId: 1831,
        displayName: "Antidote"
      }
    ]
  },
  "20035": {
    drops: [
      {
        id: "l2item_38",
        kind: "equipment",
        chance: 0.001432,
        min: 1,
        max: 1,
        chancePerMillion: 1432,
        l2ItemId: 38,
        displayName: "Low Boots"
      },
      {
        id: "l2item_50",
        kind: "equipment",
        chance: 0.001432,
        min: 1,
        max: 1,
        chancePerMillion: 1432,
        l2ItemId: 50,
        displayName: "Leather Gloves"
      },
      {
        id: "l2item_1817",
        kind: "resource",
        chance: 0.007269,
        min: 1,
        max: 1,
        chancePerMillion: 7269,
        l2ItemId: 1817,
        displayName: "Recipe: Cord"
      },
      {
        id: "thread",
        kind: "resource",
        chance: 0.072688,
        min: 1,
        max: 1,
        chancePerMillion: 72688,
        l2ItemId: 1868,
        displayName: "Thread"
      },
      {
        id: "silver_nugget",
        kind: "resource",
        chance: 0.014538,
        min: 1,
        max: 1,
        chancePerMillion: 14538,
        l2ItemId: 1873,
        displayName: "Silver Nugget"
      },
      {
        id: "l2item_1925",
        kind: "resource",
        chance: 0.031776,
        min: 1,
        max: 1,
        chancePerMillion: 31776,
        l2ItemId: 1925,
        displayName: "Leather Gloves Lining"
      },
      {
        id: "l2item_5268",
        kind: "resource",
        chance: 0.001454,
        min: 1,
        max: 1,
        chancePerMillion: 1454,
        l2ItemId: 5268,
        displayName: "Recipe: Greater Soulshot (D) Compressed Package (100%)"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 120,
        max: 193,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "thread",
        kind: "resource",
        chance: 0.492156,
        min: 1,
        max: 2,
        chancePerMillion: 492156,
        l2ItemId: 1868,
        displayName: "Thread"
      },
      {
        id: "l2item_1925",
        kind: "resource",
        chance: 0.161363,
        min: 1,
        max: 1,
        chancePerMillion: 161363,
        l2ItemId: 1925,
        displayName: "Leather Gloves Lining"
      },
      {
        id: "l2item_2140",
        kind: "resource",
        chance: 0.049216,
        min: 1,
        max: 1,
        chancePerMillion: 49216,
        l2ItemId: 2140,
        displayName: "Recipe: High Grade Suede"
      }
    ]
  },
  "20069": {
    drops: [],
    spoil: []
  },
  "20083": {
    drops: [
      {
        id: "l2item_393",
        kind: "equipment",
        chance: 0.00007,
        min: 1,
        max: 1,
        chancePerMillion: 70,
        l2ItemId: 393,
        displayName: "Mithril Banded Mail"
      },
      {
        id: "l2item_394",
        kind: "equipment",
        chance: 0.00007,
        min: 1,
        max: 1,
        chancePerMillion: 70,
        l2ItemId: 394,
        displayName: "Reinforced Leather Shirt"
      },
      {
        id: "l2item_415",
        kind: "equipment",
        chance: 0.000111,
        min: 1,
        max: 1,
        chancePerMillion: 111,
        l2ItemId: 415,
        displayName: "Mithril Banded Gaiters"
      },
      {
        id: "l2item_416",
        kind: "equipment",
        chance: 0.000111,
        min: 1,
        max: 1,
        chancePerMillion: 111,
        l2ItemId: 416,
        displayName: "Reinforced Leather Gaiters"
      },
      {
        id: "oriharukon_ore",
        kind: "resource",
        chance: 0.002882,
        min: 1,
        max: 1,
        chancePerMillion: 2882,
        l2ItemId: 1874,
        displayName: "Oriharukon Ore"
      },
      {
        id: "l2item_1878",
        kind: "resource",
        chance: 0.018182,
        min: 1,
        max: 1,
        chancePerMillion: 18182,
        l2ItemId: 1878,
        displayName: "Braided Hemp"
      },
      {
        id: "cord",
        kind: "resource",
        chance: 0.027778,
        min: 1,
        max: 1,
        chancePerMillion: 27778,
        l2ItemId: 1884,
        displayName: "Cord"
      },
      {
        id: "l2item_1889",
        kind: "resource",
        chance: 0.002309,
        min: 1,
        max: 1,
        chancePerMillion: 2309,
        l2ItemId: 1889,
        displayName: "Compound Braid"
      },
      {
        id: "l2item_1938",
        kind: "resource",
        chance: 0.003536,
        min: 1,
        max: 1,
        chancePerMillion: 3536,
        l2ItemId: 1938,
        displayName: "Mithril Banded Mail Material"
      },
      {
        id: "l2item_1939",
        kind: "resource",
        chance: 0.004619,
        min: 1,
        max: 1,
        chancePerMillion: 4619,
        l2ItemId: 1939,
        displayName: "Mithril Banded Gaiters Material"
      },
      {
        id: "l2item_2155",
        kind: "resource",
        chance: 0.007519,
        min: 1,
        max: 1,
        chancePerMillion: 7519,
        l2ItemId: 2155,
        displayName: "Recipe: Elven Ring"
      },
      {
        id: "l2item_2286",
        kind: "resource",
        chance: 0.000288,
        min: 1,
        max: 1,
        chancePerMillion: 288,
        l2ItemId: 2286,
        displayName: "Recipe: Bonebreaker"
      },
      {
        id: "l2item_2985",
        kind: "resource",
        chance: 0.00346,
        min: 1,
        max: 1,
        chancePerMillion: 3460,
        l2ItemId: 2985,
        displayName: "Recipe: Plate Boots"
      },
      {
        id: "l2item_5220",
        kind: "resource",
        chance: 0.002165,
        min: 1,
        max: 1,
        chancePerMillion: 2165,
        l2ItemId: 5220,
        displayName: "Metal Hardener"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 251,
        max: 501,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_2154",
        kind: "resource",
        chance: 0.063531,
        min: 1,
        max: 1,
        chancePerMillion: 63531,
        l2ItemId: 2154,
        displayName: "Recipe: Elven Earring"
      },
      {
        id: "l2item_2975",
        kind: "resource",
        chance: 0.052981,
        min: 1,
        max: 1,
        chancePerMillion: 52981,
        l2ItemId: 2975,
        displayName: "Recipe: Brigandine Helmet"
      },
      {
        id: "l2item_2987",
        kind: "resource",
        chance: 0.05761,
        min: 1,
        max: 1,
        chancePerMillion: 57610,
        l2ItemId: 2987,
        displayName: "Recipe: Plate Shield"
      }
    ]
  },
  "20091": {
    drops: [],
    spoil: []
  },
  "20092": {
    drops: [
      {
        id: "l2item_113",
        kind: "equipment",
        chance: 0.007148,
        min: 1,
        max: 1,
        chancePerMillion: 7148,
        l2ItemId: 113,
        displayName: "Mystic's Earring"
      },
      {
        id: "l2item_875",
        kind: "equipment",
        chance: 0.010735,
        min: 1,
        max: 1,
        chancePerMillion: 10735,
        l2ItemId: 875,
        displayName: "Ring of Knowledge"
      },
      {
        id: "l2item_906",
        kind: "equipment",
        chance: 0.005368,
        min: 1,
        max: 1,
        chancePerMillion: 5368,
        l2ItemId: 906,
        displayName: "Necklace of Knowledge"
      },
      {
        id: "animal_skin",
        kind: "resource",
        chance: 0.019323,
        min: 1,
        max: 1,
        chancePerMillion: 19323,
        l2ItemId: 1867,
        displayName: "Animal Skin"
      },
      {
        id: "iron_ore",
        kind: "resource",
        chance: 0.014493,
        min: 1,
        max: 1,
        chancePerMillion: 14493,
        l2ItemId: 1869,
        displayName: "Iron Ore"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.014493,
        min: 1,
        max: 1,
        chancePerMillion: 14493,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "charcoal",
        kind: "resource",
        chance: 0.014493,
        min: 1,
        max: 1,
        chancePerMillion: 14493,
        l2ItemId: 1871,
        displayName: "Charcoal"
      },
      {
        id: "animal_bone",
        kind: "resource",
        chance: 0.019323,
        min: 1,
        max: 1,
        chancePerMillion: 19323,
        l2ItemId: 1872,
        displayName: "Animal Bone"
      },
      {
        id: "l2item_2137",
        kind: "resource",
        chance: 0.004263,
        min: 1,
        max: 1,
        chancePerMillion: 4263,
        l2ItemId: 2137,
        displayName: "Recipe: Steel"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 79,
        max: 107,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1666",
        kind: "resource",
        chance: 0.049062,
        min: 1,
        max: 1,
        chancePerMillion: 49062,
        l2ItemId: 1666,
        displayName: "Recipe: Wooden Arrow"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.098124,
        min: 1,
        max: 1,
        chancePerMillion: 98124,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "l2item_2005",
        kind: "resource",
        chance: 0.010513,
        min: 1,
        max: 1,
        chancePerMillion: 10513,
        l2ItemId: 2005,
        displayName: "Broadsword Blade"
      }
    ]
  },
  "20093": {
    drops: [
      {
        id: "l2item_3",
        kind: "equipment",
        chance: 0.00086,
        min: 1,
        max: 1,
        chancePerMillion: 860,
        l2ItemId: 3,
        displayName: "Broadsword"
      },
      {
        id: "l2item_1060",
        kind: "resource",
        chance: 0.05972,
        min: 1,
        max: 1,
        chancePerMillion: 59720,
        l2ItemId: 1060,
        displayName: "Lesser Healing Potion"
      },
      {
        id: "animal_skin",
        kind: "resource",
        chance: 0.035832,
        min: 1,
        max: 1,
        chancePerMillion: 35832,
        l2ItemId: 1867,
        displayName: "Animal Skin"
      },
      {
        id: "animal_bone",
        kind: "resource",
        chance: 0.035832,
        min: 1,
        max: 1,
        chancePerMillion: 35832,
        l2ItemId: 1872,
        displayName: "Animal Bone"
      },
      {
        id: "l2item_2005",
        kind: "resource",
        chance: 0.00384,
        min: 1,
        max: 1,
        chancePerMillion: 3840,
        l2ItemId: 2005,
        displayName: "Broadsword Blade"
      },
      {
        id: "l2item_2138",
        kind: "resource",
        chance: 0.007905,
        min: 1,
        max: 1,
        chancePerMillion: 7905,
        l2ItemId: 2138,
        displayName: "Recipe: Coarse Bone Powder (100%)"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 98,
        max: 132,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1666",
        kind: "resource",
        chance: 0.060652,
        min: 1,
        max: 1,
        chancePerMillion: 60652,
        l2ItemId: 1666,
        displayName: "Recipe: Wooden Arrow"
      },
      {
        id: "animal_skin",
        kind: "resource",
        chance: 0.242609,
        min: 1,
        max: 1,
        chancePerMillion: 242609,
        l2ItemId: 1867,
        displayName: "Animal Skin"
      },
      {
        id: "l2item_2007",
        kind: "resource",
        chance: 0.012997,
        min: 1,
        max: 1,
        chancePerMillion: 12997,
        l2ItemId: 2007,
        displayName: "Bow Shaft"
      }
    ]
  },
  "20094": {
    drops: [],
    spoil: []
  },
  "20095": {
    drops: [
      {
        id: "l2item_428",
        kind: "equipment",
        chance: 0.001808,
        min: 1,
        max: 1,
        chancePerMillion: 1808,
        l2ItemId: 428,
        displayName: "Feriotic Tunic"
      },
      {
        id: "l2item_463",
        kind: "equipment",
        chance: 0.002889,
        min: 1,
        max: 1,
        chancePerMillion: 2889,
        l2ItemId: 463,
        displayName: "Feriotic Stockings"
      },
      {
        id: "l2item_1100",
        kind: "equipment",
        chance: 0.001808,
        min: 1,
        max: 1,
        chancePerMillion: 1808,
        l2ItemId: 1100,
        displayName: "Cotton Tunic"
      },
      {
        id: "l2item_1103",
        kind: "equipment",
        chance: 0.002889,
        min: 1,
        max: 1,
        chancePerMillion: 2889,
        l2ItemId: 1103,
        displayName: "Cotton Stockings"
      },
      {
        id: "l2item_1789",
        kind: "resource",
        chance: 0.005412,
        min: 1,
        max: 1,
        chancePerMillion: 5412,
        l2ItemId: 1789,
        displayName: "Recipe: Cedar Staff"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.058548,
        min: 1,
        max: 1,
        chancePerMillion: 58548,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "iron_ore",
        kind: "resource",
        chance: 0.029274,
        min: 1,
        max: 1,
        chancePerMillion: 29274,
        l2ItemId: 1869,
        displayName: "Iron Ore"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 80,
        max: 108,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "stem",
        kind: "resource",
        chance: 0.297315,
        min: 1,
        max: 1,
        chancePerMillion: 297315,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "l2item_2006",
        kind: "resource",
        chance: 0.010618,
        min: 1,
        max: 1,
        chancePerMillion: 10618,
        l2ItemId: 2006,
        displayName: "Willow Staff Head"
      }
    ]
  },
  "20096": {
    drops: [
      {
        id: "l2item_37",
        kind: "equipment",
        chance: 0.002996,
        min: 1,
        max: 1,
        chancePerMillion: 2996,
        l2ItemId: 37,
        displayName: "Leather Shoes"
      },
      {
        id: "l2item_49",
        kind: "equipment",
        chance: 0.002996,
        min: 1,
        max: 1,
        chancePerMillion: 2996,
        l2ItemId: 49,
        displayName: "Gloves"
      },
      {
        id: "l2item_736",
        kind: "resource",
        chance: 0.009924,
        min: 1,
        max: 1,
        chancePerMillion: 9924,
        l2ItemId: 736,
        displayName: "Scroll of Escape"
      },
      {
        id: "animal_skin",
        kind: "resource",
        chance: 0.026464,
        min: 1,
        max: 1,
        chancePerMillion: 26464,
        l2ItemId: 1867,
        displayName: "Animal Skin"
      },
      {
        id: "iron_ore",
        kind: "resource",
        chance: 0.019848,
        min: 1,
        max: 1,
        chancePerMillion: 19848,
        l2ItemId: 1869,
        displayName: "Iron Ore"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.019848,
        min: 1,
        max: 1,
        chancePerMillion: 19848,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "charcoal",
        kind: "resource",
        chance: 0.019848,
        min: 1,
        max: 1,
        chancePerMillion: 19848,
        l2ItemId: 1871,
        displayName: "Charcoal"
      },
      {
        id: "animal_bone",
        kind: "resource",
        chance: 0.026464,
        min: 1,
        max: 1,
        chancePerMillion: 26464,
        l2ItemId: 1872,
        displayName: "Animal Bone"
      },
      {
        id: "l2item_1921",
        kind: "resource",
        chance: 0.025611,
        min: 1,
        max: 1,
        chancePerMillion: 25611,
        l2ItemId: 1921,
        displayName: "Leather Shoes Texture"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 109,
        max: 147,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1792",
        kind: "resource",
        chance: 0.014822,
        min: 1,
        max: 1,
        chancePerMillion: 14822,
        l2ItemId: 1792,
        displayName: "Recipe: Short Spear"
      },
      {
        id: "l2item_1799",
        kind: "resource",
        chance: 0.298635,
        min: 1,
        max: 1,
        chancePerMillion: 298635,
        l2ItemId: 1799,
        displayName: "Recipe: Leather Gloves"
      },
      {
        id: "l2item_1921",
        kind: "resource",
        chance: 0.130051,
        min: 1,
        max: 1,
        chancePerMillion: 130051,
        l2ItemId: 1921,
        displayName: "Leather Shoes Texture"
      }
    ]
  },
  "20099": {
    drops: [
      {
        id: "l2item_66",
        kind: "equipment",
        chance: 0.00013,
        min: 1,
        max: 1,
        chancePerMillion: 130,
        l2ItemId: 66,
        displayName: "Gladius"
      },
      {
        id: "l2item_1333",
        kind: "equipment",
        chance: 0.00013,
        min: 1,
        max: 1,
        chancePerMillion: 130,
        l2ItemId: 1333,
        displayName: "Brandish"
      },
      {
        id: "l2item_1794",
        kind: "resource",
        chance: 0.001287,
        min: 1,
        max: 1,
        chancePerMillion: 1287,
        l2ItemId: 1794,
        displayName: "Recipe: Forest Bow"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.035,
        min: 1,
        max: 1,
        chancePerMillion: 35000,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.0175,
        min: 1,
        max: 1,
        chancePerMillion: 17500,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.011667,
        min: 1,
        max: 1,
        chancePerMillion: 11667,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "thread",
        kind: "resource",
        chance: 0.035,
        min: 1,
        max: 1,
        chancePerMillion: 35000,
        l2ItemId: 1868,
        displayName: "Thread"
      },
      {
        id: "silver_nugget",
        kind: "resource",
        chance: 0.007,
        min: 1,
        max: 1,
        chancePerMillion: 7000,
        l2ItemId: 1873,
        displayName: "Silver Nugget"
      },
      {
        id: "l2item_2010",
        kind: "resource",
        chance: 0.001363,
        min: 1,
        max: 1,
        chancePerMillion: 1363,
        l2ItemId: 2010,
        displayName: "Brandish Blade"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 95,
        max: 131,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "soulshot_ng",
        kind: "resource",
        chance: 0.473949,
        min: 1,
        max: 1,
        chancePerMillion: 473949,
        l2ItemId: 1831,
        displayName: "Antidote"
      },
      {
        id: "spiritshot_ng",
        kind: "resource",
        chance: 0.07531,
        min: 1,
        max: 1,
        chancePerMillion: 75310,
        l2ItemId: 1896,
        displayName: "Necklace of Anguish Chain"
      },
      {
        id: "l2item_2009",
        kind: "resource",
        chance: 0.006303,
        min: 1,
        max: 1,
        chancePerMillion: 6303,
        l2ItemId: 2009,
        displayName: "Dirk Blade"
      }
    ]
  },
  "20100": {
    drops: [
      {
        id: "l2item_271",
        kind: "equipment",
        chance: 0.000411,
        min: 1,
        max: 1,
        chancePerMillion: 411,
        l2ItemId: 271,
        displayName: "Hunting Bow"
      },
      {
        id: "l2item_1799",
        kind: "resource",
        chance: 0.05495,
        min: 1,
        max: 1,
        chancePerMillion: 54950,
        l2ItemId: 1799,
        displayName: "Recipe: Leather Gloves"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.024728,
        min: 1,
        max: 1,
        chancePerMillion: 24728,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "charcoal",
        kind: "resource",
        chance: 0.037091,
        min: 1,
        max: 1,
        chancePerMillion: 37091,
        l2ItemId: 1871,
        displayName: "Charcoal"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 99,
        max: 140,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1792",
        kind: "resource",
        chance: 0.013849,
        min: 1,
        max: 1,
        chancePerMillion: 13849,
        l2ItemId: 1792,
        displayName: "Recipe: Short Spear"
      },
      {
        id: "l2item_1833",
        kind: "resource",
        chance: 0.502269,
        min: 1,
        max: 1,
        chancePerMillion: 502269,
        l2ItemId: 1833,
        displayName: "Bandage"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.125567,
        min: 1,
        max: 1,
        chancePerMillion: 125567,
        l2ItemId: 1866,
        displayName: "Suede"
      }
    ]
  },
  "20120": {
    drops: [
      {
        id: "l2item_13",
        kind: "equipment",
        chance: 0.010394,
        min: 1,
        max: 1,
        chancePerMillion: 10394,
        l2ItemId: 13,
        displayName: "Short Bow"
      },
      {
        id: "l2item_1060",
        kind: "resource",
        chance: 0.022174,
        min: 1,
        max: 1,
        chancePerMillion: 22174,
        l2ItemId: 1060,
        displayName: "Lesser Healing Potion"
      },
      {
        id: "l2item_1786",
        kind: "resource",
        chance: 0.007983,
        min: 1,
        max: 1,
        chancePerMillion: 7983,
        l2ItemId: 1786,
        displayName: "Recipe: Broad Sword"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.009979,
        min: 1,
        max: 1,
        chancePerMillion: 9979,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.009979,
        min: 1,
        max: 1,
        chancePerMillion: 9979,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 19,
        max: 29,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1787",
        kind: "resource",
        chance: 0.030885,
        min: 1,
        max: 1,
        chancePerMillion: 30885,
        l2ItemId: 1787,
        displayName: "Recipe: Willow Staff"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.077212,
        min: 1,
        max: 1,
        chancePerMillion: 77212,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "oriharukon_ore",
        kind: "resource",
        chance: 0.002574,
        min: 1,
        max: 1,
        chancePerMillion: 2574,
        l2ItemId: 1874,
        displayName: "Oriharukon Ore"
      }
    ]
  },
  "20432": {
    drops: [
      {
        id: "l2item_11",
        kind: "equipment",
        chance: 0.004286,
        min: 1,
        max: 1,
        chancePerMillion: 4286,
        l2ItemId: 11,
        displayName: "Bone Dagger"
      },
      {
        id: "l2item_17",
        kind: "resource",
        chance: 0.011757,
        min: 10,
        max: 30,
        chancePerMillion: 11757,
        l2ItemId: 17,
        displayName: "Wooden Arrow"
      },
      {
        id: "l2item_1787",
        kind: "resource",
        chance: 0.001881,
        min: 1,
        max: 1,
        chancePerMillion: 1881,
        l2ItemId: 1787,
        displayName: "Recipe: Willow Staff"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.004703,
        min: 1,
        max: 1,
        chancePerMillion: 4703,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "varnish",
        kind: "resource",
        chance: 0.002352,
        min: 1,
        max: 1,
        chancePerMillion: 2352,
        l2ItemId: 1865,
        displayName: "Varnish"
      },
      {
        id: "suede",
        kind: "resource",
        chance: 0.001568,
        min: 1,
        max: 1,
        chancePerMillion: 1568,
        l2ItemId: 1866,
        displayName: "Suede"
      },
      {
        id: "thread",
        kind: "resource",
        chance: 0.004703,
        min: 1,
        max: 1,
        chancePerMillion: 4703,
        l2ItemId: 1868,
        displayName: "Thread"
      },
      {
        id: "silver_nugget",
        kind: "resource",
        chance: 0.000941,
        min: 1,
        max: 1,
        chancePerMillion: 941,
        l2ItemId: 1873,
        displayName: "Silver Nugget"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 8,
        max: 12,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: []
  },
  "20481": {
    drops: [
      {
        id: "l2item_426",
        kind: "equipment",
        chance: 0.011197,
        min: 1,
        max: 1,
        chancePerMillion: 11197,
        l2ItemId: 426,
        displayName: "Tunic"
      },
      {
        id: "l2item_462",
        kind: "equipment",
        chance: 0.01789,
        min: 1,
        max: 1,
        chancePerMillion: 17890,
        l2ItemId: 462,
        displayName: "Stockings"
      },
      {
        id: "l2item_17",
        kind: "resource",
        chance: 0.020574,
        min: 10,
        max: 30,
        chancePerMillion: 20574,
        l2ItemId: 17,
        displayName: "Wooden Arrow"
      },
      {
        id: "l2item_1786",
        kind: "resource",
        chance: 0.003292,
        min: 1,
        max: 1,
        chancePerMillion: 3292,
        l2ItemId: 1786,
        displayName: "Recipe: Broad Sword"
      },
      {
        id: "thread",
        kind: "resource",
        chance: 0.00823,
        min: 1,
        max: 1,
        chancePerMillion: 8230,
        l2ItemId: 1868,
        displayName: "Thread"
      },
      {
        id: "silver_nugget",
        kind: "resource",
        chance: 0.001646,
        min: 1,
        max: 1,
        chancePerMillion: 1646,
        l2ItemId: 1873,
        displayName: "Silver Nugget"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 8,
        max: 12,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1786",
        kind: "resource",
        chance: 0.012736,
        min: 1,
        max: 1,
        chancePerMillion: 12736,
        l2ItemId: 1786,
        displayName: "Recipe: Broad Sword"
      },
      {
        id: "l2item_1788",
        kind: "resource",
        chance: 0.012736,
        min: 1,
        max: 1,
        chancePerMillion: 12736,
        l2ItemId: 1788,
        displayName: "Recipe: Bow"
      },
      {
        id: "thread",
        kind: "resource",
        chance: 0.031839,
        min: 1,
        max: 1,
        chancePerMillion: 31839,
        l2ItemId: 1868,
        displayName: "Thread"
      }
    ]
  },
  "20544": {
    drops: [
      {
        id: "l2item_21",
        kind: "equipment",
        chance: 0.019065,
        min: 1,
        max: 1,
        chancePerMillion: 19065,
        l2ItemId: 21,
        displayName: "Shirt"
      },
      {
        id: "l2item_28",
        kind: "equipment",
        chance: 0.030461,
        min: 1,
        max: 1,
        chancePerMillion: 30461,
        l2ItemId: 28,
        displayName: "Pants"
      },
      {
        id: "l2item_1788",
        kind: "resource",
        chance: 0.007474,
        min: 1,
        max: 1,
        chancePerMillion: 7474,
        l2ItemId: 1788,
        displayName: "Recipe: Bow"
      },
      {
        id: "stem",
        kind: "resource",
        chance: 0.018683,
        min: 1,
        max: 1,
        chancePerMillion: 18683,
        l2ItemId: 1864,
        displayName: "Stem"
      },
      {
        id: "iron_ore",
        kind: "resource",
        chance: 0.009342,
        min: 1,
        max: 1,
        chancePerMillion: 9342,
        l2ItemId: 1869,
        displayName: "Iron Ore"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 13,
        max: 20,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1788",
        kind: "resource",
        chance: 0.021685,
        min: 1,
        max: 1,
        chancePerMillion: 21685,
        l2ItemId: 1788,
        displayName: "Recipe: Bow"
      },
      {
        id: "coal",
        kind: "resource",
        chance: 0.027106,
        min: 1,
        max: 1,
        chancePerMillion: 27106,
        l2ItemId: 1870,
        displayName: "Coal"
      },
      {
        id: "animal_bone",
        kind: "resource",
        chance: 0.036142,
        min: 1,
        max: 1,
        chancePerMillion: 36142,
        l2ItemId: 1872,
        displayName: "Animal Bone"
      }
    ]
  },
  "20545": {
    drops: [
      {
        id: "l2item_18",
        kind: "equipment",
        chance: 0.042201,
        min: 1,
        max: 1,
        chancePerMillion: 42201,
        l2ItemId: 18,
        displayName: "Leather Shield"
      },
      {
        id: "l2item_41",
        kind: "equipment",
        chance: 0.029925,
        min: 1,
        max: 1,
        chancePerMillion: 29925,
        l2ItemId: 41,
        displayName: "Cloth Cap"
      },
      {
        id: "l2item_17",
        kind: "resource",
        chance: 0.016459,
        min: 10,
        max: 30,
        chancePerMillion: 16459,
        l2ItemId: 17,
        displayName: "Wooden Arrow"
      },
      {
        id: "l2item_1788",
        kind: "resource",
        chance: 0.002634,
        min: 1,
        max: 1,
        chancePerMillion: 2634,
        l2ItemId: 1788,
        displayName: "Recipe: Bow"
      },
      {
        id: "thread",
        kind: "resource",
        chance: 0.006584,
        min: 1,
        max: 1,
        chancePerMillion: 6584,
        l2ItemId: 1868,
        displayName: "Thread"
      },
      {
        id: "silver_nugget",
        kind: "resource",
        chance: 0.001317,
        min: 1,
        max: 1,
        chancePerMillion: 1317,
        l2ItemId: 1873,
        displayName: "Silver Nugget"
      },
      {
        id: "l2item_6037",
        kind: "resource",
        chance: 0.006584,
        min: 1,
        max: 1,
        chancePerMillion: 6584,
        l2ItemId: 6037,
        displayName: "Waking Scroll"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 8,
        max: 12,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: []
  },
  "20546": {
    drops: [
      {
        id: "l2item_849",
        kind: "equipment",
        chance: 0.000235,
        min: 1,
        max: 1,
        chancePerMillion: 235,
        l2ItemId: 849,
        displayName: "Tiger's Eye Earring"
      },
      {
        id: "l2item_880",
        kind: "equipment",
        chance: 0.000353,
        min: 1,
        max: 1,
        chancePerMillion: 353,
        l2ItemId: 880,
        displayName: "Black Pearl Ring"
      },
      {
        id: "l2item_912",
        kind: "equipment",
        chance: 0.000177,
        min: 1,
        max: 1,
        chancePerMillion: 177,
        l2ItemId: 912,
        displayName: "Near Forest Necklace"
      },
      {
        id: "mithril_ore",
        kind: "resource",
        chance: 0.010989,
        min: 1,
        max: 1,
        chancePerMillion: 10989,
        l2ItemId: 1876,
        displayName: "Mithril Ore"
      },
      {
        id: "adamantite_nugget",
        kind: "resource",
        chance: 0.0005,
        min: 1,
        max: 1,
        chancePerMillion: 500,
        l2ItemId: 1877,
        displayName: "Adamantite Nugget"
      },
      {
        id: "steel",
        kind: "resource",
        chance: 0.004,
        min: 1,
        max: 1,
        chancePerMillion: 4000,
        l2ItemId: 1880,
        displayName: "Steel"
      },
      {
        id: "coarse_bone_powder",
        kind: "resource",
        chance: 0.003003,
        min: 1,
        max: 1,
        chancePerMillion: 3003,
        l2ItemId: 1881,
        displayName: "Coarse Bone Powder"
      },
      {
        id: "leather",
        kind: "resource",
        chance: 0.010989,
        min: 1,
        max: 1,
        chancePerMillion: 10989,
        l2ItemId: 1882,
        displayName: "Leather"
      },
      {
        id: "l2item_1901",
        kind: "resource",
        chance: 0.010426,
        min: 1,
        max: 1,
        chancePerMillion: 10426,
        l2ItemId: 1901,
        displayName: "Tiger's Eye Earring Stone"
      },
      {
        id: "l2item_2274",
        kind: "resource",
        chance: 0.00027,
        min: 1,
        max: 1,
        chancePerMillion: 270,
        l2ItemId: 2274,
        displayName: "Recipe: Skull Breaker"
      },
      {
        id: "l2item_2276",
        kind: "resource",
        chance: 0.00027,
        min: 1,
        max: 1,
        chancePerMillion: 270,
        l2ItemId: 2276,
        displayName: "Recipe: Maingauche"
      },
      {
        id: "l2item_2976",
        kind: "resource",
        chance: 0.006494,
        min: 1,
        max: 1,
        chancePerMillion: 6494,
        l2ItemId: 2976,
        displayName: "Recipe: Manticore Skin Boots"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 240,
        max: 478,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "adamantite_nugget",
        kind: "resource",
        chance: 0.022714,
        min: 1,
        max: 1,
        chancePerMillion: 22714,
        l2ItemId: 1877,
        displayName: "Adamantite Nugget"
      },
      {
        id: "l2item_2279",
        kind: "resource",
        chance: 0.004056,
        min: 1,
        max: 1,
        chancePerMillion: 4056,
        l2ItemId: 2279,
        displayName: "Recipe: War Pick"
      },
      {
        id: "l2item_2979",
        kind: "resource",
        chance: 0.076017,
        min: 1,
        max: 1,
        chancePerMillion: 76017,
        l2ItemId: 2979,
        displayName: "Recipe: Manticore Skin Gloves"
      }
    ]
  },
  "20924": {
    drops: [
      {
        id: "l2item_259",
        kind: "equipment",
        chance: 0.000049,
        min: 1,
        max: 1,
        chancePerMillion: 49,
        l2ItemId: 259,
        displayName: "Single-Edged Jamadhr"
      },
      {
        id: "mithril_ore",
        kind: "resource",
        chance: 0.003947,
        min: 1,
        max: 1,
        chancePerMillion: 3947,
        l2ItemId: 1876,
        displayName: "Mithril Ore"
      },
      {
        id: "adamantite_nugget",
        kind: "resource",
        chance: 0.00079,
        min: 1,
        max: 1,
        chancePerMillion: 790,
        l2ItemId: 1877,
        displayName: "Adamantite Nugget"
      },
      {
        id: "steel",
        kind: "resource",
        chance: 0.001974,
        min: 1,
        max: 1,
        chancePerMillion: 1974,
        l2ItemId: 1880,
        displayName: "Steel"
      },
      {
        id: "coarse_bone_powder",
        kind: "resource",
        chance: 0.002631,
        min: 1,
        max: 1,
        chancePerMillion: 2631,
        l2ItemId: 1881,
        displayName: "Coarse Bone Powder"
      },
      {
        id: "leather",
        kind: "resource",
        chance: 0.004385,
        min: 1,
        max: 1,
        chancePerMillion: 4385,
        l2ItemId: 1882,
        displayName: "Leather"
      },
      {
        id: "l2item_2183",
        kind: "resource",
        chance: 0.001299,
        min: 1,
        max: 1,
        chancePerMillion: 1299,
        l2ItemId: 2183,
        displayName: "Recipe: Mithril Banded Mail"
      },
      {
        id: "l2item_2274",
        kind: "resource",
        chance: 0.000141,
        min: 1,
        max: 1,
        chancePerMillion: 141,
        l2ItemId: 2274,
        displayName: "Recipe: Skull Breaker"
      },
      {
        id: "l2item_6667",
        kind: "resource",
        chance: 0.012658,
        min: 1,
        max: 1,
        chancePerMillion: 12658,
        l2ItemId: 6667,
        displayName: "Deluxe Chest Key - Grade 3"
      },
      {
        id: "adena",
        kind: "adena",
        chance: 0.7,
        min: 122,
        max: 244,
        chancePerMillion: 700000,
        l2ItemId: 57,
        displayName: "Adena"
      }
    ],
    spoil: [
      {
        id: "l2item_1900",
        kind: "resource",
        chance: 0.031603,
        min: 1,
        max: 1,
        chancePerMillion: 31603,
        l2ItemId: 1900,
        displayName: "Enchanted Necklace Chain"
      },
      {
        id: "l2item_1937",
        kind: "resource",
        chance: 0.024815,
        min: 1,
        max: 1,
        chancePerMillion: 24815,
        l2ItemId: 1937,
        displayName: "Scale Gaiters Fragment"
      },
      {
        id: "l2item_2250",
        kind: "resource",
        chance: 0.072213,
        min: 1,
        max: 1,
        chancePerMillion: 72213,
        l2ItemId: 2250,
        displayName: "Recipe: Bone Arrow"
      }
    ]
  }
} as const satisfies Record<number, L2XmlNpcDrops>;
