/**
 * Generates GK teleport cost maps from l2dop data (no TS import of mobs).
 * Run: node tools/buildGkTeleportCosts.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const worldL2 = path.join(root, "src", "data", "world", "l2dop");

const zoneFiles = [
  "zones.ts",
  "giranZones.ts",
  "dionZones.ts",
  "heineZones.ts",
  "schuttgartZones.ts",
  "runeZones.ts",
  "floranVillageZones.ts",
  "gludinVillageZones.ts",
  "huntersVillageZones.ts",
  "goddardEliteZones.ts",
  "ancientTombFieldsZones.ts",
].map((f) => path.join(worldL2, f));

const zoneCosts = {};

function parseZoneLine(line) {
  const idM = line.match(/id:\s*"([^"]+)"/);
  const tpM = line.match(/tp:\s*([0-9_]+)/);
  if (idM && tpM) {
    const id = idM[1];
    const tp = Number(tpM[1].replace(/_/g, ""));
    if (!Number.isFinite(tp)) return;
    zoneCosts[id] = tp;
  }
}

for (const file of zoneFiles) {
  const text = fs.readFileSync(file, "utf8");
  for (const line of text.split("\n")) {
    if (line.includes("id:") && line.includes("tp:")) parseZoneLine(line);
  }
}

const eliteText = fs.readFileSync(path.join(worldL2, "goddardEliteZones.ts"), "utf8");
let em;
const eliteRe = /id:\s*"([^"]+)"[\s\S]*?tp:\s*([0-9_]+)/g;
while ((em = eliteRe.exec(eliteText)) !== null) {
  const id = em[1];
  const tp = Number(em[2].replace(/_/g, ""));
  if (id.startsWith("l2dop_goddard_")) zoneCosts[id] = tp;
}

const cityCosts = {};
for (const line of fs.readFileSync(path.join(worldL2, "cities.ts"), "utf8").split("\n")) {
  if (!line.includes("tpCost:") || !line.includes("id:")) continue;
  const idM = line.match(/id:\s*"([^"]+)"/);
  const tpM = line.match(/tpCost:\s*([0-9_]+)/);
  if (idM && tpM) cityCosts[idM[1]] = Number(tpM[1].replace(/_/g, ""));
}

function emitRecord(name, obj) {
  const keys = Object.keys(obj).sort();
  const lines = keys.map((k) => `  "${k}": ${obj[k]},`);
  return `export const ${name}: Readonly<Record<string, number>> = {\n${lines.join("\n")}\n};\n`;
}

const clientOut = `// AUTO-GENERATED by tools/buildGkTeleportCosts.mjs — do not edit by hand
${emitRecord("GK_ZONE_TP_COSTS_GENERATED", zoneCosts)}
`;
const clientPath = path.join(root, "src", "data", "world", "gkZoneTpCosts.generated.ts");
fs.writeFileSync(clientPath, clientOut, "utf8");

const serverOut = `// AUTO-GENERATED by tools/buildGkTeleportCosts.mjs — do not edit by hand
${emitRecord("GK_TELEPORT_CITY_COSTS", cityCosts)}
${emitRecord("GK_TELEPORT_ZONE_COSTS", zoneCosts)}
`;
const serverPath = path.join(root, "server", "src", "gkTeleportCosts.generated.ts");
fs.writeFileSync(serverPath, serverOut, "utf8");

console.log("Wrote", clientPath, "zones:", Object.keys(zoneCosts).length);
console.log("Wrote", serverPath, "cities:", Object.keys(cityCosts).length, "zones:", Object.keys(zoneCosts).length);
